CREATE TABLE tb_usuario (
    ID_USUARIO SERIAL
    CONSTRAINT pk_id_usuario PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
    SOBRENOME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    RENDA NUMERIC(8,2) 
);

CREATE TABLE tb_plano_financeiro (
    ID_PLANO SERIAL
    CONSTRAINT pk_id_plano PRIMARY KEY,
    DESCRICAO VARCHAR(20),
    ID_USUARIO SERIAL,
    CONSTRAINT fk_plano_usuario
    FOREIGN KEY (ID_USUARIO)
    REFERENCES tb_usuario(ID_USUARIO)
);